# Generated by Django 3.0.5 on 2020-05-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='specialty',
        ),
    ]
